### ISSUE TITLE
Doesn't import under Python 3

### ISSUE THREAD

**Issue by OddBloke** [rubyruy/treecompare#2]
```pycon
Python 3.5.3+ (default, Jun  7 2017, 23:23:48) 
[GCC 6.3.0 20170519] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import treecompare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/.virtualenvs/mypy/lib/python3.5/site-packages/treecompare/__init__.py", line 24, in <module>
    from .differ import make_differ
  File "/home/daniel/.virtualenvs/mypy/lib/python3.5/site-packages/treecompare/differ.py", line 1, in <module>
    from . import implementations as impl
  File "/home/daniel/.virtualenvs/mypy/lib/python3.5/site-packages/treecompare/implementations.py", line 98, in <module>
    class DiffNumbers(DiffPrimitives):
  File "/home/daniel/.virtualenvs/mypy/lib/python3.5/site-packages/treecompare/implementations.py", line 99, in DiffNumbers
    diffs_types = (int, long, float)
NameError: name 'long' is not defined
```

**Comment by ramanshah** [comment]
I'm curious about this too! (Interested in potentially diffing some trees for a recurring back-office chore.) Is this package being maintained? It looks to be <500 lines of Python. Adapting the build/test harness and debugging our way into Python 3 support would feel like a worthy package of open source effort - if there's a path to getting the changes into PyPI.

**Comment by ramanshah** [comment]
I forked this repo today and have filed a task in my personal project management to break down a Python 3 port into actionable steps. Note it's a very low-urgency chore I need this for, so I can't guarantee it will happen soon or quickly.

Would love input from any other watchers on this - I think the goal of this package merits its maintenance as Python moves forward, and I in particular would rather use it than hand-roll some junky ad hoc tree diffing stuff. Judging by the above date stamps, this repo appears abandoned, but please correct me if I'm wrong. I'd far prefer to contribute through PRs than maintaining a fork but will do the latter if it's the best way forward.

**Comment by froh** [comment]
@ramanshah how did it go?  did you find an alternative or did you pull through?

**Comment by ramanshah** [comment]
Sigh I never did get moving on this. I wish I had, as I could still use it for that chore.

With the benefit of a few years' new development, do you know of any competitors to this tool? Thanks!
